[package]
name = "qwex"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
qwxl = { version = "0.1.0", path = "../../lib/qwxl" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing = "0.1.44"
