name: lifecycle

tasks:
  gen_id:
    run: date "+%Y%m%d_%H%M%S_$(head -c 4 /dev/urandom | xxd -p)"

  init:
    run: |
      echo "init $1"

  start:
    run: |
      echo "start $1"

  finish:
    run: |
      echo "finish $1 $2"

  status:
    run: |
      echo "unknown"

