services:
  ssh-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh_test_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY_FILE=/authorized_keys/id_rsa.pub
      - USER_NAME=testuser
      - PASSWORD_ACCESS=false
    volumes:
      - ./demo/.ssh/id_rsa.pub/:/authorized_keys/id_rsa.pub:ro
    ports:
      - 2345:22
    restart: unless-stopped
